### PR TITLE
API-12088 Add Custom Exceptions

### PR DESCRIPTION
**Pull request by bwisnaskas-va**

### CODE REVIEW

**Review by esubocz-va — APPROVED** [review]

**Comment by esubocz-va** [comment]
I think this should be a major upgrade.

**Comment by bwisnaskas-va** [comment]
Ho do I go about making it a major upgrade?

**Comment by dlennon-va** [comment]
> Ho do I go about making it a major upgrade?

Update this [line](https://github.com/department-of-veterans-affairs/lighthouse-benefits-gateway-services/blob/master/pom.xml#L11) to 5.0.0-SNAPSHOT

**Comment by bschofield-va** [comment]
> > Ho do I go about making it a major upgrade?
> 
> Update this [line](https://github.com/department-of-veterans-affairs/lighthouse-benefits-gateway-services/blob/master/pom.xml#L11) to 5.0.0-SNAPSHOT

You have to update all of the poms to match.

Here are two command line ways ...

Using the Versions plugin
```
mvn versions:set -DnewVersion=5.0.0-SNAPSHOT -DprocessAllModules=true
```

Old School
```
sed -i 's/4.0.1-SNAPSHOT/5.0.0-SNAPSHOT/' $(git ls-files | grep pom.xml)
```

**Comment by bwisnaskas-va** [comment]
I have updated the poms to be version 5.0.0-SNAPSHOT

**Review by esubocz-va — APPROVED** [review]

**Pull request merged**
